# Generated by Django 5.1 on 2024-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artists_id', models.IntegerField()),
                ('studio_id', models.IntegerField()),
                ('lable', models.CharField(max_length=15)),
                ('release', models.IntegerField()),
                ('genre', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('year1', models.IntegerField()),
                ('year2', models.IntegerField()),
                ('active', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('writer', models.CharField(max_length=20)),
                ('lyrics', models.TextField()),
                ('length', models.DateTimeField()),
            ],
        ),
    ]
