# Generated by Django 5.1 on 2024-08-15 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнителей'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': 'Студия звукозаписи', 'verbose_name_plural': 'Студий звукозаписи'},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'verbose_name': 'Композиция', 'verbose_name_plural': 'Композиции'},
        ),
        migrations.RemoveField(
            model_name='artists',
            name='price',
        ),
        migrations.AlterField(
            model_name='albums',
            name='artists_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_recordings.artists'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='genre',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='lable',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Лэйбл'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Цена за диск'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='release',
            field=models.IntegerField(null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='studio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_recordings.studio'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='active',
            field=models.BooleanField(verbose_name='Продолжают работать'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='city',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='country',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='year1',
            field=models.IntegerField(null=True, verbose_name='Год начала деятельности'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='year2',
            field=models.IntegerField(null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='city',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='country',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Студия звукозаписи'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_recordings.albums'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='length',
            field=models.DateTimeField(null=True, verbose_name='Длительность звучания'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='lyrics',
            field=models.TextField(default='N/A', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер композиции п/п'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='writer',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Композитор/Поэт'),
        ),
    ]
